version: '2.3'

services:
        ros-master:
                image: ros:kinetic-ros-core
                container_name: ros-master
                hostname: ros-master
                networks:
                        - roscomm
                ports:
                        - 11311:11311
                command: roscore

        ros-mb-sim:
                image: repohub.enterpriselab.ch:5002/kawa/ros-kinetic-mb-sim-gl:latest
                runtime: nvidia
                depends_on:
                        - ros-master
                container_name: ros-mb-sim
                hostname: ros-mb-sim
                networks:
                        - roscomm
                environment:
                        - DISPLAY=unix:0
                        - QT_X11_NO_MITSHM=1
                        - XAUTHORITY=/tmp/.docker.xauth
                        - ROS_HOSTNAME=ros-mb-sim
                        - ROS_MASTER_URI=http://ros-master:11311
                volumes:
                        - /tmp/.X11-unix:/tmp/.X11-unix:rw
                        - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
                command: /run-shells/run-sim-hmi.sh

        rosbridge-server:
                image: repohub.enterpriselab.ch:5002/kawa/rosbridge-kinetic-server:latest
                depends_on:
                        - ros-master
                container_name: rosbridge-server
                hostname: rosbridge-server
                networks:
                        - roscomm
                ports:
                        - 9090:9090
                        - 9091:9091
                environment:
                        - ROS_HOSTNAME=rosbridge-server
                        - ROS_MASTER_URI=http://ros-master:11311
                        - VIRTUAL_HOST=rosbridge-server.local
                command: /run-shells/run-rosbridge-server.sh

        web-missions-dashboard:
                image: repohub.enterpriselab.ch:5002/kawa/web-missions-dashboard:latest
                depends_on:
                        - rosbridge-server
                container_name: web-missions-dashboard
                hostname: web-missions-dashboard
                networks:
                        - roscomm
                ports:
                        - 8081:8080

        nginx-proxy:
                image: repohub.enterpriselab.ch:5002/kawa/nginx-reverse-proxy:latest
                depends_on:
                        - web-missions-dashboard
                container_name: nginx-proxy
                hostname: nginx-proxy
                networks:
                        - roscomm
                ports:
                        - 80:80

networks:
        roscomm:

volumes:
        maps:
        poses:

